set(Live555_URL "https://download.videolan.org/contrib/live555/live.2023.01.19.tar.gz")
set(Live555_file "live555-master")
set(Live555_CFLAGS -DNEWLOCALE_NOT_USED=1 -DBSD=1 -DSOCKLEN_T=socklen_t -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE=1 -DNO_SSTREAM=1 -DALLOW_RTSP_SERVER_PORT_REUSE=1 -DNO_GETIFADDRS=1 -DNO_OPENSSL=1 CACHE STRING "live555 CFGLAGS")
set(Live555_DIR  "${CMAKE_SOURCE_DIR}/3rdparty/live555" CACHE INTERNAL "")    

if(CMAKE_CXX_STANDARD LESS 20)
    list(APPEND Live555_CFLAGS -DNO_STD_LIB)
endif()

# function for download Live555
if (NOT EXISTS ${Live555_DIR})
    message(STATUS "Live555 not found. downloading ... ")
    file (DOWNLOAD ${Live555_URL} ${CMAKE_SOURCE_DIR}/${Live555_file}.tar.gz )
    EXECUTE_PROCESS(COMMAND ${CMAKE_COMMAND} -E tar xvf ${CMAKE_SOURCE_DIR}/${Live555_file}.tar.gz RESULT_VARIABLE result OUTPUT_QUIET)
    if(NOT result STREQUAL "0")
        message(FATAL_ERROR "Fetching and compiling Live555 failed!")
    endif()        
    file(REMOVE ${CMAKE_SOURCE_DIR}/${Live555_file}.tar.gz)
    execute_process(COMMAND ${CMAKE_COMMAND} -E copy_directory "${Live555_file}" "${Live555_DIR}")        
    execute_process(COMMAND ${CMAKE_COMMAND} -E remove_directory "${Live555_file}")
endif()  
